apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: combined-pool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.20.200-192.168.20.250
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: combined-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
    - combined-pool
  interfaces:
    - ens33
